---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ministryofjustice/analytical-platform-actions-runner
  tag: 2.317.0

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 10000

resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
  requests:
    cpu: 500m
    memory: 2000Mi

github:
  organisation:
  repository:
  token:
  runner:
    labels:

ephemeral: false

maxReplicaCount: 5
pollingInterval: 30