---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ministryofjustice/analytical-platform-actions-runner
  tag: 2.320.0-3

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  name: ""
  annotations:
    checkov.io/skip1: "CKV_K8S_21=Default namespace is not used when deploying with Helm"

podAnnotations: {}
podLabels: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 10000

resources:
  requests:
    cpu: 1
    memory: "5Gi"
  limits:
    cpu: 2
    memory: "7Gi"

github:
  organisation:
  repository:
  tokenSecretName: actions-runners-token-apc-self-hosted-runners
  tokenSecretKey: token
  runner:
    labels:

ephemeral:
  enabled: true
  karpenter:
    enabled: true
    nodePool: "general-spot"
  keda:
    maxReplicaCount: 15
    pollingInterval: 20
