---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ministryofjustice/analytical-platform-actions-runner
  tag: 2.319.1-1

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 10000

resources:
  requests:
    cpu: 1
    memory: "5Gi"
  limits:
    cpu: 2
    memory: "7Gi"

github:
  organisation:
  repository:
  token:
  runner:
    labels:

runner:
  cache:
    enabled: true
    agentToolsDirectory: /actions-runner/_tools
    pvcName: actions-runner-cache

ephemeral:
  enabled: true
  karpenter:
    enabled: true
    nodePool: "general-spot"
  keda:
    maxReplicaCount: 15
    pollingInterval: 20
