apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-auth
  namespace: keda-actions-runners
data:
  personalAccessToken: ${GITHUB_TOKEN}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: github-trigger-auth
  namespace: keda-actions-runners
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: github-auth
      key: personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: scaledjob-github-runner
  namespace: keda-actions-runners
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: scaledjob-github-runner
      spec:
        containers:
        - name: scaledjob-github-runner
          image: ghcr.io/ministryofjustice/analytical-platform-actions-runner:2.317.0-ephermal-rc2
          imagePullPolicy: Always
          env:
          - name: EPHEMERAL
            value: "true"
          - name: GITHUB_REPOSITORY
            value: "ministryofjustice/test-keda-runner"
          - name: RUNNER_LABELS
            value: "ephemeral-runner-test"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-auth
                key: personalAccessToken
        restartPolicy: Never
  successfulJobsHistoryLimit: 0
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 30
  triggers:
  - type: github-runner
    metadata:
      owner: "ministryofjustice"
      repos: "test-keda-runner"
      labels: "ephemeral-runner-test" 
      runnerScope: "repo" 
    authenticationRef:
      name: github-trigger-auth
