{{- if .Values.ephemeral.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Release.Name }}-github-trigger-auth
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: {{ .Release.Name }}-github-token
      key: token
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ include "actions-runner.fullname" . }}
  labels:
    {{- include "actions-runner.labels" . | nindent 4 }}
spec:
  jobTargetRef:
    template:
      metadata:
        {{- with .Values.podAnnotations }}
        annotations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        labels:
          {{- include "actions-runner.labels" . | nindent 8 }}
    {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
      spec:
        serviceAccountName: {{ include "actions-runner.serviceAccountName" . }}
        containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources:
              {{- toYaml .Values.resources | nindent 12 }}
            env:
              - name: EPHEMERAL
                value: "true"
              - name: GITHUB_REPOSITORY
                value: {{ .Values.github.organisation }}/{{ .Values.github.repository }}
              - name: RUNNER_LABELS
                value: {{ .Values.github.runner.labels | quote }}
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-github-token
                    key: token
              {{- if .Values.runner.cache.enabled }}
              - name: AGENT_TOOLSDIRECTORY
                value: {{ .Values.runner.cache.agentToolsDirectory }}
              {{- end }}
            {{- if .Values.runner.cache.enabled }}
            volumeMounts:
              - name: actions-runner-cache
                mountPath: {{ .Values.runner.cache.agentToolsDirectory }}
            {{- end }}
        {{- if .Values.runner.cache.enabled }}
        volumes:
          - name: actions-runner-cache
            persistentVolumeClaim:
              claimName: {{ .Values.runner.cache.pvcName }}
        {{- end }}
        {{- if .Values.ephemeral.karpenter.enabled }}
        restartPolicy: Never
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool
                      operator: In
                      values:
                        - {{ .Values.ephemeral.karpenter.nodePool }}
        tolerations:
          - key: compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool
            operator: "Equal"
            value: {{ .Values.ephemeral.karpenter.nodePool }}
            effect: "NoSchedule"
        {{- end }}
  successfulJobsHistoryLimit: 0
  minReplicaCount: 0
  maxReplicaCount: {{ .Values.ephemeral.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.ephemeral.keda.pollingInterval }}
  triggers:
    - type: github-runner
      metadata:
        owner: {{ .Values.github.organisation }}
        repos: {{ .Values.github.repository }}
        labels: {{ .Values.github.runner.labels | quote }}
        runnerScope: "repo"
      authenticationRef:
        name: {{ .Release.Name }}-github-trigger-auth
{{- end }}
