---
github:
  organisation: ministryofjustice
  repository: analytical-platform
  token: this-is-not-a-real-token
  runner:
    labels: "self-hosted,analytical-platform"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/this-is-not-a-real-role
