---
github:
  organisation: ministryofjustice
  repository: analytical-platform
  tokenSecretName: this-is-not-a-real-secret-name
  tokenSecretKey: token
  runner:
    labels: "self-hosted,analytical-platform"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/this-is-not-a-real-role

hostAliases:
  - ip: "127.0.0.1"
    hostnames:
      - "foo.local"
      - "bar.local"
  - ip: "127.0.0.2"
    hostnames:
      - "baz.local"
      - "qux.local"
