---
name: Build and Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set Up Container Structure Test
        id: setup_container_structure_test
        uses: ministryofjustice/github-actions/setup-container-structure-test@c9cb317b93b19d1c28b7a42b0c982bdff8106bbb # v18.0.1

      - name: Build and Test
        id: build_and_test
        shell: bash
        run: |
          make test
