---
name: Build and Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set Up Container Structure Test
        id: setup_container_structure_test
        uses: ministryofjustice/github-actions/setup-container-structure-test@5b9e53c0aec9316e7f18cb03f5513599c89d989d # v18.1.0

      - name: Build and Test
        id: build_and_test
        shell: bash
        run: |
          make test
