---
name: 🗺️ Chart Lint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  chart-lint:
    name: Chart Lint
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/chart-lint.yml@f81658c938374c2f5a69b0ad8e2c89948e29aad0 # v4.0.10
