---
name: 🗺️ Chart Lint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  chart-lint:
    name: Chart Lint
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-chart-lint.yml@497b26456c1f0cff118cf5f663b66794d368f3e8 # v8.0.2
