---
name: 🗺️ Chart Lint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  chart-lint:
    name: Chart Lint
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-chart-lint.yml@8465086d84a8ae8fb993ef582f00cf13b8ceb9c8 # v7.1.0
