---
name: 🩻 Container Scan

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-scan:
    name: Container Scan
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-container-scan.yml@9e604949e842733e0990f5eb6627844e8715deeb # v6.4.0
