---
name: 🧪 Container Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-test:
    name: Container Test
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/container-test.yml@f81658c938374c2f5a69b0ad8e2c89948e29aad0 # v4.0.10
