---
name: 🔍 Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-dependency-review.yml@497b26456c1f0cff118cf5f663b66794d368f3e8 # v8.0.2
