---
name: 🛡️ OpenSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * 1"

permissions: {}

jobs:
  openssf-scorecard:
    name: OpenSSF Scorecard
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/openssf-scorecard.yml@f81658c938374c2f5a69b0ad8e2c89948e29aad0 # v4.0.10
