---
name: Release Chart

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  release-chart:
    name: Release Chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set Up Helm
        id: setup_helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0

      - name: Log in to GitHub Container Registry
        id: login_ghcr
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Chart
        id: package_chart
        run: |
          helm package chart --destination .helm-deploy

      - name: Push Chart
        id: push_chart
        run: |
          helm push .helm-deploy/actions-runner-${{ github.ref_name }}.tgz oci://ghcr.io/ministryofjustice/analytical-platform-charts
