---
name: 🩻 Scan

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1-5" # Every weekday at 9AM UTC

permissions: {}

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Clean Actions Runner
        id: clean_actions_runner
        uses: ministryofjustice/github-actions/clean-actions-runner@db1a54895bf5fb975c60af47e5a3aab96505ca3e # v18.6.0
        with:
          confirm: true

      - name: Build
        id: build
        shell: bash
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make build

      - name: Scan
        id: scan
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # v0.30.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Slack CVE Alert
        if: failure() && github.event_name == 'schedule' && steps.scan.outcome == 'failure'
        id: slack_cve_alert
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.CVE_SCAN_SLACK_WEBHOOK_URL }}
          payload: |
            {
              "repository": "${{ github.repository }}",
              "run_id": "${{ github.run_id }}"
            }
