---
name: 🦝 Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@9e604949e842733e0990f5eb6627844e8715deeb # v6.4.0
    with:
      # VALIDATE_KUBERNETES_KUBECONFORM is set to false as it cannot process Helm charts
      super-linter-variables: |
        {
          "VALIDATE_KUBERNETES_KUBECONFORM": false
        }
