---
name: 🧪 Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set Up Container Structure Test
        id: setup_container_structure_test
        uses: ministryofjustice/github-actions/setup-container-structure-test@63d84d475bc20877f741d768dd9c2d89af51170d # v18.2.0

      - name: Test
        id: test
        shell: bash
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make test
