---
name: 🧪 Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set Up Container Structure Test
        id: setup_container_structure_test
        uses: ministryofjustice/github-actions/setup-container-structure-test@e633262ca3b8a050eeb148b3a79c046942cdfa34 # v18.1.3

      - name: Test
        id: test
        shell: bash
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make test
